In [1]:
import pandas as pd 
import numpy as np

In [16]:
data = pd.read_csv('E:\Github Repositories\Quack-Quack\Machine Learning\Model - 3\Datasets\Final_data\combined_data.csv', index_col=False)
data.head()

,React,Next.js,Javascript/Typescript,Express.js,Python,Flask/FastAPI,PostgreSQL/MongoDB,AWS,GCP,Azure,...,OpenCV,Prisma,TailwindCss,Recoil,Redux,TanStack Query,Zustand,Socket.io,Hono.js,Score
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,22
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,15
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,27
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,1

In [17]:
data.isnull().sum()

React                    0
Next.js                  0
Javascript/Typescript    0
Express.js               0
Python                   0
Flask/FastAPI            0
PostgreSQL/MongoDB       0
AWS                      0
GCP                      0
Azure                    0
Tensorflow/Pytorch       0
OpenCV                   0
Prisma                   0
TailwindCss              0
Recoil                   0
Redux                    0
TanStack Query           0
Zustand                  0
Socket.io                0
Hono.js                  0
Score                    0
dtype: int64